[build]
target = "riscv64imac-unknown-none-elf"

[unstable]
build-std = ["core,panic_abort"]
build-std-features = ["panic_immediate_abort"]

[target.riscv64imac-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "target-feature=+m,+a,+c,+b", "-C", "linker=lld"]
