[package]
name = "test_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
riscv = "0.13.0"

[profile.release]
panic = "abort"
debug = 2
lto = true
codegen-units = 1
opt-level = "s"
overflow-checks = false
