[project]
name = "bubbly_test_rs"
version = "0.1.0"
description = "Running rust tests on Bubbly"
requires-python = ">=3.8,<4"
dependencies = [
    "argparse>=1.4.0",
    "lief~=0.16",
    "colorama~=0.4"
]
