[project]
name = "bubbly_riscof"
version = "0.1.0"
description = "Running riscv-arch-test on Bubbly"
requires-python = "~=3.8"
dependencies = [
    "riscv-config~=3.18",
    "riscof~=1.25",
    "gitpython==3.1.17",
    "ruamel.yaml==0.17.40",
    "lief~=0.16"
]
